import { Html, Head, Main, NextScript } from 'next/document'

import type { Metadata } from 'next'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function Document() {
  return (
    <Html>
      <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
        />
        <link rel="icon" href="/favicon.ico" />
        <meta
          name="title"
          property="og:title"
          content="Marco Faltoni | FrontEnd Developer & Industrial Designer"
        />
        <meta
          name="description"
          content="Web Space di Marco Faltoni, FrontEnd Developer & 3D Designer, appasionato di Web, Tecnologia e Design"
        />
        <meta property="og:description" content="Hey sono Marco Faltoni e sono un front end web developer&Designer. Visita la mia pagina LinkedIn per vedere i miei progetti in JavaScript, React e Next" />
        <meta name="format-detection" content="telephone=no" />
        <meta property="og:image" content="/social-image.jpg" />
        <meta property="og:type" content="website" />

      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}